jobs:
  setup:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Backend Dependencies
          command: |
            cd BACKEND
            npm install
            

  backend-tests:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Clean node_modules
          command: |
            cd BACKEND
            rm -rf node_modules
      - run:
          name: Install Backend Dependencies
          command: |
            cd BACKEND
            npm install
      - run:
          name: Ensure Jest Binary Has Execute Permissions
          command: |
            cd BACKEND
            if [ -f node_modules/.bin/jest ]; then chmod +x node_modules/.bin/jest; fi
      - run:
          name: Run Backend Tests
          command: |
            cd BACKEND
            ./node_modules/.bin/jest --config jest.backend.config.cjs

  frontend-tests:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Frontend Dependencies
          command: |
            cd "FRONT END/frontend"
            npm install
      - run:
          name: Ensure Jest Binary Has Execute Permissions
          command: |
            cd "FRONT END/frontend"
            if [ -f node_modules/.bin/jest ]; then chmod +x node_modules/.bin/jest; fi
      - run:
          name: Run Frontend Login Tests
          command: |
            cd "FRONT END/frontend"
            ./node_modules/.bin/jest --testPathPattern='FRONT END/frontend/tests/frontendLogin.test.js'
      - run:
          name: Run Frontend Register Tests
          command: |
            cd "FRONT END/frontend"
            ./node_modules/.bin/jest --testPathPattern='FRONT END/frontend/tests/frontendRegister.test.js'
      - run:
          name: Run Frontend Payment Tests
          command: |
            cd "FRONT END/frontend"
            npm run test -- --testPathPattern='FRONT END/frontend/tests/frontendPayment.test.js'

workflows:
  version: 2
  test-and-build:
    jobs:
      - setup
      - backend-tests:
          requires:
            - setup
      - frontend-tests:
          requires:
            - setup
