version: 2.1

jobs:
  say-hello:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Print Hello World
          command: echo "Hello, World!"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
