version: 2.1

jobs:
  setup:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Backend Dependencies
          command: |
            cd BACKEND
            npm install
      - run:
          name: Ensure Jest Binary Has Execute Permissions
          command: |
            if [ -f node_modules/.bin/jest ]; then chmod +x node_modules/.bin/jest; fi
      - run:
          name: Run Backend Tests
          command: |
            cd BACKEND
            npm test

workflows:
  version: 2
  test-and-build:
    jobs:
      - setup
      - backend-tests:
          requires:
            - setup